### ISSUE TITLE
[FEATURE] Ability to have multiple calendars

### ISSUE THREAD

**Issue by JulianQuispel** [JulianQuispel/notion-ical#1]
Currently you can only sync one Notion database to your calendar. It would be nice to be able to have multiple Notion databases in your calendar. It would be nice to configure multiple calendars in an easy format, like YAML. An example:
```yaml
calendars:
  tasks:
    name: Tasks
    database_id: ts2g0xplq6qcwb8flmhwddvuiz09auh0
    properties:
      date: Date
  workouts:
    name: Workouts
    database_id: ts2g0xplq6qcwb8flmhwddvuiz09auh0
    properties:
      date: Date
```
